### PR TITLE
Add mermaid support, rendering in sandbox iframe

### PR DESCRIPTION
**Pull request by jmandel**
This will pick up any ".mermaid" elements in the HTML site, which means it'll pick up any `<div class="mermaid">` blocks in the source markdown.

### CODE REVIEW

**Comment by jmandel** [comment]
@grahamegrieve are we good to merge this now? We were waiting for an IG publisher release I think.

**Comment by grahamegrieve** [comment]
were we? why? I don't know anything about this anyway

**Comment by jmandel** [comment]
We discussed; you approved https://github.com/FHIR/ig-guidance/pull/36 which documents the new behavior. This PR is what implements the new behavior.

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
