### PR TITLE
Add support for jekyll data files

### PR DESCRIPTION
**Pull request by costateixeira**
from IG (input/data) or from template (package/data)
only tested with json files

### CODE REVIEW

**Comment by lmckenzi** [comment]
Why are you using 'extensionOf' in the same script the extension point is defined in?  Just add it as a dependency like all of the others...

**Comment by costateixeira** [comment]
what should I make it dependOn ?

**Comment by lmckenzi** [comment]
It won't dependOn anything - other stuff will dependOn it :)

**Comment by costateixeira** [comment]
I couldn't figure out which would be the next step in the sequence. Can you
change it or let me know where to change?
Or should we just leave it without any dependencies in or out (which I
presume means: "run this first as a parallel thing" - is that correct)?

Thanks

**Comment by lmckenzi** [comment]
Just add it to the depends list on onGenerate.extend

**Comment by costateixeira** [comment]
check now please

**Pull request merged**
