### PR TITLE
Fix annoying flicker at page load

### PR DESCRIPTION
**Pull request by costateixeira**

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
When smooth transitions were introduced, there was also a change on the <body/> element - should that also be removed?

**Comment by costateixeira** [comment]
change on the element? I don't understand that. 

the last commit added back the style on the segment-content. I did remove the onload="document.body.style.opacity='1'" in the <body> tag because I think it doesn't hurt (and because in the past I had some issues with it). it can also be removed but I did not test it

**Comment by lmckenzi** [comment]
That's what I'm referring to - " <body onload="document.body.style.opacity='1'">" got added in https://github.com/HL7/ig-template-base/pull/114 and you've rolled back most of it, so wondering if we should roll that part back too.  If you can try & test, that'd be appreciated.

**Comment by costateixeira** [comment]
there was a quote missing, thanks.
While I'm testing it, I still don't understand what this means:
> That's what I'm referring to - " " got added in #114 
the only other thing that got loaded is the opacity. I deliberately left it there because of past pain in templates that looked all black.
Perhaps that is now harmless, but I left it anyway.

**Comment by costateixeira** [comment]
but I can remove that change if you want to really go back to the previous state before  #114

**Comment by costateixeira** [comment]
@lmckenzi tested locally (just updated my local package cache accordingly), works
(i did not follow the procedure to make a branch, use that branch and download it, because at this time I can't remember that procedure)

**Review by lmckenzi — APPROVED** [review]
Looks ok

**Pull request merged**
