### PR TITLE
Feedback form

### PR DESCRIPTION
**Pull request by costateixeira**

### CODE REVIEW

**Comment by costateixeira** [comment]
Introduces the feedback option, starting with a google forms input. 
The initial script had javascript content as variables, which could be used to inject code. The current script only allows variables that are an integer or one of the allowed variables (sectionName, sectionId, pageTitle)
The documentation will follow.

**Comment by costateixeira** [comment]
@lmckenzi this is ready to approve

**Review by lmckenzi — CHANGES_REQUESTED** [review]
The footer change needs to put the vertical bar inside the 'if'.  Would like Grahame to vet the script and make sure he's comfortable that an ill-intentioned IG author couldn't cause nasty things to happen with it.

**Comment by costateixeira** [comment]
There are tuo bars, one outside and another inside the IF. 
image
I put the last one inside, but perhaps it's better to put the first one instead, and remove the last one altogether.

For vetting the google forms script, i am just now adding some comments to the code

**Comment by costateixeira** [comment]
The code now has some comments
https://github.com/HL7/ig-template-base/pull/137/commits/b564c7dd7f247a77afd8e9fd9eed6383e580ae38

**Comment by costateixeira** [comment]
@grahamegrieve I commented the code for clarity, can you please review? This code is to be fed by a yaml file that contains the coordinates for feedback. Example: 
```yaml
---
feedback:
  - active: true
    type: "googleform"   
    label: "Feedback"   
    formUrl: https://docs.google.com/forms/d/e/1FAIpQLScmCYc6opgnln2iKCLc1sUXD8fA27TJU4h7O63Lk4DD7MaZWw/viewform?usp=pp_url
    dashboard: 
      url: https://github.com/who-int/svc/projects/1
      label: "Issues"    
    parameters:
    - fieldId: "1353807103"
      variableName: "pageTitle"
    - fieldId: "247644557"
      variableName: "sectionName"
```
the variableNames have only a few possible values, the fieldIds are cast as integers just to make sure they are not containing anything strange. I don't know if there are any residual risks.
This is to be used by the WHO Vaccination Certificate so i made it my priority to address this. Alternatively we can also add it to the WHO IG template, but we'd need to make that template trusted.

Thanks

**Review by costateixeira — COMMENTED** [review]
ok

**Pull request merged**
