### PR TITLE
add liquid to hide empty inv tables

### PR DESCRIPTION
**Pull request by Healthedata1**
foo

### CODE REVIEW

**Comment by Healthedata1** [comment]
this is a liquid solution

**Comment by lmckenzi** [comment]
The section you highlighted in the diagram wasn't actually empty.  I'm not sure we want to hide 'inherited' invariants.  Those are still relevant.  (Though it would be nice if we could distinguish inherited ones from new/changed ones.)

**Comment by Healthedata1** [comment]
what I am illustrating is that when there are constraints the table is rendered and when there are none the table is not rendered.  this occur most often when the parameter 

    - code: show-inherited-invariants
      value: 'false'

**Comment by Healthedata1** [comment]
here is an example of an empty table that would be hidden...

image

**Comment by lmckenzi** [comment]
So, to clarify, this change will cause empty tables to not appear, but *won't* prevent inherited invariants from showing, correct?  And the default in the base is to always show inherited invariants and the requirement for HL7 IGs would be to always show inherited invariants - correct?

**Comment by Healthedata1** [comment]
>
> So, to clarify, this change will cause empty tables to not appear, but
> *won't* prevent inherited invariants from showing, correct?


 Correct

And the default in the base is to always show inherited invariants and the
> requirement for HL7 IGs would be to always show inherited invariants -
> correct?

I think that is a separate discussion.  The
parameter 'show-inherited-invariants'  exists with default = true and is
not prohibitd for use.


Eric


Eric M Haas, DVM, MS
Health eData Inc
35 Crescent Avenue, Sausalito, CA 94965
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com

**Comment by lmckenzi** [comment]
I think HL7-published IGs need to be consistent about always publishing all invariants.  It may be the best solution is to combine the list of invariants into the tabs that show snapshot vs. differential vs. 'mustSupport' so that you can look at the invariants pertinent to the view.  But having a published IG that doesn't show *all* of the invariants is a problem, no matter how noisy they might be.

**Pull request merged**
