### PR TITLE
Add TestScript layout and navigation tabs to linked resources

### PR DESCRIPTION
**Pull request by rettema**
### What does this Pull Request do?
Add components that incorporates TestScript resources to the FHIR Artifacts page, adds new page navigation tab "TestScripts" if TestScript resources are found linked to FHIR conformance resources, and add a new TestScript layout pages based pm linked resource type.

### Why?
The FHIR community has been increasingly interested in provided better support for testing artifacts within IGs. These additional components are an initial enhancement that allows IGs generated from the HL7 IG template to incorporate and list TestScript resources as first class artifacts and with their associated/scoped FHIR resources.

### How?
New and updated components:
* **./config.json** - _Updated_
  * "**extraTemplates**" list - add new object for { "name": "testing", "description": "Testing" }
  * "**defaults**" list - update all canonical FHIR resource types to add new attributes: "template-testing", "testing"; add new "Testing" layout
* **./includes/fragment-base-navtabs.html** - _Updated_
  * New **Testing** navigation tab logic - displays the new "Testing" nav tab only if linked testscript list size > 0
* **./includes/fragment-profile-navtabs.html** - _Updated_
  * New **Testing** navigation tab logic - displays the new "Testing" nav tab only if linked testscript list size > 0
* **./layouts/layout-canonical-testing.html** - _Updated / Renamed_
  * New layout for Testing page - currently displays TestScript resources linked to FHIR canonical resource types
* _./layouts/layout-codesystem-testscripts.html_ - **_Removed_**
  * _New layout for TestScript resources linked to FHIR CodeSystem resources_
* _./layouts/layout-instance-testing.html_ - **_Removed_**
  * _New layout for Testing page - currently displays TestScript resources linked to FHIR non-canonical resource types_
* **./layouts/layout-profile-testing.html** - _Updated / Renamed_
  * New layout for Testing page - currently displays TestScript resources linked to FHIR Profiles (StructureDefinitions)
* _./layouts/layout-valueset-testscripts.html_ - **_Removed_**
  * _New layout for TestScript resources linked to FHIR ValueSet resources_
* **./scripts/groupings.txt**
  * Add new **grouping** element "-test-testscript" - for FHIR Artifacts page, section "Testing Artifacts: TestScripts"
* **./scripts/onGenerate.greoup.xslt**
  * Add new "**groupingId**" variable assignment "-test-testscript" when resource is a 'TestScript' - works in conjunction with **groupings.txt** new **grouping** element (see previous bullet)

### Dependencies
These modifications are dependent on the IG Publisher tool modifications in the Pull Request https://github.com/HL7/fhir-ig-publisher/pull/518 now incorporated into the current (version 1.2.9+) IG Publisher tool.

### CODE REVIEW

**Comment by costateixeira** [comment]
This closes the loop directly between Conformance resources and TestScripts.

In case that we want to make an indirect link - from Conformance Resource
to something that "wraps" a test plan or test instructions (which can
contain 0..* testscripts) (aka a test plan), would this be incompatible?
If so, can we quickly see what to do to prepare for that?

Kind regards

José

**Comment by rettema** [comment]
Jose,

These updates and additions are focused on simply rendering TestScripts as a list to those other resources that have been "scoped" as well as providing a suitable TestScript layout page. I don't believe this will be incompatible with any future additions to incorporate "test plans" and/or "test instructions".

Kind regards,
Richard

**Comment by costateixeira** [comment]
This is a step forward, and I assume that later we can see what we'd change. My only attention point is about the tabs and organization of content - see below 
Here's how it looks like for testing a questionnaire:
image

A few things I notice:

* The text says "TestScripts for the food-allergy-questionnaire **ValueSet**" ? This is a questionnaire.
* the link uses the id of the testscript - Maybe it should use the name / title instead?
* The tab is called TestScripts - if we have a "test plan" then we could end up with two extra tabs - one for Testing, one for TestScripts? or would it be the same tab?

**Comment by rettema** [comment]
Yes, the current logic for showing the Testing tab is based on N TestScripts > 0. This can be updated / enhanced to include "Test Plans" once we figure out what they are.

I like the idea of "TestPlan" as a profile - either List or Composition - my initial leaning might be towards List.

I fully expect this to continue to evolve and, yes, that may likely mean "TestPlan(s)" could supersede this initial TestScript enhancement.

**Comment by costateixeira** [comment]
I think the perspective of adding a new resource / profile that supersedes
it confirms that this is OK as change:
We can have the link between Artifacts and TestScripts now, and we work on
a TestPlan and then we do for TestPlan exactly the same as we do here.
This way, authors can choose to either use test plan or just testscripts,
and the publisher behaves consistently

I'd favour this PR to be merged as is now, and we continue to work on
TestPlan

**Review by lmckenzi — COMMENTED** [review]
The instance layout is used for examples.  Presumably we don't want examples to have a testing page.  Is this going to generate a bunch of empty pages that we just don't have any links to?

**Comment by costateixeira** [comment]
I didn't think of that. I hope this adds the page only for conformance
resources

**Comment by rettema** [comment]
Lloyd,
Yes, the current modifications do include the Testing page on example resources. I will remove and commit that later today.
Thanks.

**Review by lmckenzi — APPROVED** [review]
Looks ok

**Pull request merged**
