### PR TITLE
remove automatic adding of external link icons

### PR DESCRIPTION
**Pull request by costateixeira**

### CODE REVIEW

**Comment by lmckenzi** [comment]
Why would we want to do that?

**Comment by costateixeira** [comment]
https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/where.20is.20this.20html.3F

**Comment by costateixeira** [comment]
some external limks may not want that icon. I have this for example in my feedback css.
we can override, but see the chat - i don't know the impact of this

**Comment by lmckenzi** [comment]
I would much rather have a way to override and turn it off.  We don't want designers to have to remember to turn it on (or get it right)

**Comment by Healthedata1** [comment]
the css I allows you to turn it off and I don't want to have to manually turn it on.
the current css assumes absolute references are external.
turns off with style no-external= "true" and no-download="true"

I am not   not ok with this pr

**Comment by Healthedata1** [comment]
we just have to identify were the hard coded externals are in the footer and remove them or add no-external="true" to fix the issue.

**Comment by lmckenzi** [comment]
That's already been done.  I'm going to close this as I don't think any further action is required.  (Jose or Eric - are no-external and no-download documented in ig-guidance? - that should be done to help those who follow after.)

**Pull request closed without merging**
