### PR TITLE
Update for md rendering

### PR DESCRIPTION
**Pull request by Healthedata1**
it turns out ...

removing   {::options parse_block_html="true" /}  in the page-md.html template makes the markdownify work  i.e. render all the markdown correctly for pages ...

what does it do?...

also  added comments to the pagebegin comments  to help navigating it

also fixed the markdown includes for notes and intros into the extensions ( plus comments )

I tested across:

1. [x] My IG Template4
1. [x] ig-sampler
1. [x] using  auto- publisher ( see comment on GitHub  issue below)
1. [X] sushi - my copy of subscriptions.

other issues I discovered:

####  checking across browsers I noticed section numbering not working for ie.

tried to fix this first  ... not working and is a to do ...

####  all my md pages  are leaking into the output folder
 - messes up github pages and I imagine the ig pub too
 for example all these files in my test IG are in output:
~~~
> find output -name "*.md" -print
~~~

-  output/StructureDefinition-identifier-status-intro.md
-  output/operations.md
-  output/StructureDefinition-template-basic-notes.md
-  output/profiles.md
-  output/guidance.md
-  output/capstatements.md
-  output/StructureDefinition-template-profile-on-profile-intro.md
-  output/StructureDefinition-ext-complex-intro.md
-  output/StructureDefinition-ext-identifier-status-intro.md
-  output/terminology.md
-  output/StructureDefinition-ext-blah-intro.md
-  output/StructureDefinition-identifier-status-notes.md
-  output/index.md
-  output/ifr-intro.md
-  output/StructureDefinition-template-basic-intro.md
-  output/downloads.md
-  output/StructureDefinition-template-profile-on-profile-notes.md
-  output/all-examples.md
-  output/ifr-search.md
-  output/searchparameters.md

This ig-sampler doesn't behave this way and I don't know why...  will post on Zulip.

#### issue when xml page in the ig resource page.generation code define it be "xml" not "html" which is how ig-pub is implemented.  

so the input/pagecontent/file.xml is in ig resource is ...

~~~
- nameUrl: file.html
  title: File
  generation: html
~~~

I think is confusing to have the xml and generation different... I will create and issue after posting on Zulip

#### markdownify filter can produces invalid (and inappropriate) HTML

When Markdown is used for section headings, for example, the markdownify filter produces invalid (and inappropriate) HTML by wrapping the output in a paragraph tag. 

To solve this if your markdown start with something other than a paragraph  adding  a line break

### CODE REVIEW

**Comment by Healthedata1** [comment]
I also added comment to fragment-header.html trying to get it Github to download it along with rest of the include folder.  Not sure if this was the issue, but in the end had to delete commit/push and add/commit/push to get it to work for testing the autopublishing.

**Comment by lmckenzi** [comment]
- Try testing using the CRD IG - in particular check the rendering of the JSON content.  
- I don't understand the change to the README?
- It looks like your changes will cause H2 to be the start level for numbering instead of H3 - that'll break a ton of IGs.  Is that the case?  If so, we need to have a community discussion about whether everyone is comfortable changing all of the IGs that use the template to now use H2 as the root.  (Right now the publisher hollers if XHTML content contains H1s or H2s.  Haven't figured out how to do that for markdown yet.)
- Not a fan of a whole bunch of comments in the header and other fragments - it bulks up all the pages.  Is it really needed?  If we must have comments, let's make them as concise as possible.

**Comment by Healthedata1** [comment]
- OK the CRD looks good,  except for my 'fix' for the  section numbering (see next bullet below)
- here is the reason for the change:  
update_for_markdown3

in short If an HTML tag has an attribute markdown="1", then the default
 mechanism for parsing syntax in this tag is used.  Don't need the {::options } 
 inner declaration.

- I didn't realize that it was suppose to be h3's I though it was h2's ( my markdown pages all start with ## but used to render as h3s and I never liked this)  I will revert back to the h3s.  

- I am a fan of comment in html since it makes it easer to figure out what each section does for future maintainers especially for those of us with aging eyesight.  Also I think the pages are long enough that it comes in handy.

- also github ignore empty files so will need to add a comment  to `fragment-header .html` so when you test the repo it gets added to the template.

- still haven't debugged why my markdown files are leaking into the output, I have a suspicious the ig-pub is greedy about pages...

**Comment by lmckenzi** [comment]
The example template shown doesn't seem to correlate with the template.  The template substitution should be rooted with a <ul/> tag.  Surrounding that with <p/> shouldn't cause a problem.  The injection of <p/> into the list seems to be something else.  That said, we shouldn't be using the extension list, profile list, etc. at all because they're subsumed by the artifact list page.

In any rate, how does that relate to H2 vs. H3?

**Comment by Healthedata1** [comment]
I will break this pr into multiple small ones

**Pull request closed without merging**
