### PR TITLE
Md render fix2

### PR DESCRIPTION
**Pull request by Healthedata1**
there were several places where the notes and intro were not markdown compatible. 
- made the  notes and intros html  include files
- added the markdown="1' tag so the markdown file can have includes.
- tested on CRD, and sample igs with no known side effects.

### CODE REVIEW

**Comment by Healthedata1** [comment]
I have no idea why there are conflicts

**Comment by Healthedata1** [comment]
after reviewing the conflicts - easy to fix here.

**Comment by lmckenzi** [comment]
Easy for you, perhaps...  Go ahead :)

**Comment by Healthedata1** [comment]
ty!

**Comment by Healthedata1** [comment]
conflicts fixed

**Pull request merged**
