### PR TITLE
Add R5 TestPlan to Testing Artifacts

### PR DESCRIPTION
**Pull request by rettema**
### What does this Pull Request do?
Add components that incorporates TestPlan resources to the FHIR Artifacts page, adds a new listing of TestPlan resources to the FHIR Profile page navigation tab "Testing" if TestPlan resources are found linked to the FHIR Profile, and add a new TestPlan layout page.

### Why?
The FHIR community has been increasingly interested in provided better support for testing artifacts within IGs. These additional components are an additional enhancement that allows IGs generated from the HL7 IG template to incorporate and list TestPlan resources as first class artifacts and with their associated FHIR Profiles (StructureDefinitions).

### How?
Updated components:
* **./config.json** 
* **./includes/fragment-canonical-navtabs.html**
* **./includes/fragment-profile-navtabs.html**
* **./layouts/layout-profile-canonical.html**
* **./layouts/layout-profile-testscripts.html**
* **./scripts/groupings.txt**
* **./scripts/onGenerate.greoup.xslt**

### Dependencies
These modifications are dependent on the IG Publisher tool modifications in the Pull Request https://github.com/HL7/fhir-ig-publisher/pull/676

### CODE REVIEW

**Comment by costateixeira** [comment]
Can we expose more about the testplan / testscript ? I am specifically looking at category, which we can use in the testing tab to drive some liquid to e.g. group the test plans in the testing tab. 
We don't need to figure out all the rendering options, just expose some data from the Java publisher that allows the template to  then do the rest.

**Comment by rettema** [comment]
Per ig tooling call on 5/16, will create additional profiles in the example IG showing the combinations where a profile has:

- No TestPlans or TestScripts
- Has at least one TestPlan and no TestScripts
- Has no TestPlans and at least one TestScript
- Has at least one TestPlan and at least one TestScript

**Comment by rettema** [comment]
Per ig tooling call on 5/16, the combinations of conformance resources to TestPlan and TestScript have been added to the DevDays 2023 "Developer Satisfaction ... version 0.3.0" example IG. This version 0.3.0 of the IG has been deployed to the public WildFHIR v4 FHIR Server where the given links are live.

- No TestPlans or TestScripts
  - New Goal Profile added
  - http://wildfhir4.aegis.net/ig/dev-satisfaction-r4/0.3.0/StructureDefinition-dev-satisfaction-goal.html
- Has at least one TestPlan and no TestScripts
  - The 'requirements' CapabilityStatement is only referenced from one TestPlan
  - http://wildfhir4.aegis.net/ig/dev-satisfaction-r4/0.3.0/CapabilityStatement-dev-satisfaction-server-r4.html
- Has no TestPlans and at least one TestScript
  - The $get-satisfaction OperationDefinition is only referenced from two TestScripts
  - http://wildfhir4.aegis.net/ig/dev-satisfaction-r4/0.3.0/OperationDefinition-dev-satisfaction-get-satisfaction.html
- Has at least one TestPlan and at least one TestScript
  - The existing Observation Profile is referenced from one TestPlan and four TestScripts
  - http://wildfhir4.aegis.net/ig/dev-satisfaction-r4/0.3.0/StructureDefinition-dev-satisfaction-observation.html

**Comment by rettema** [comment]
Per IG tooling call on 2023-06-13, will update the "Testing" tab headers to simply be "Test Plans" and "Test Scripts" and display as true headers. Will also update the lists of TestPlan and TestScript resource links to display the corresponding title element value.

**Comment by rettema** [comment]
Per IG tooling call on 2023-06-20:
- Additional issue with fhir-ig-publisher needs to be addressed - https://github.com/HL7/fhir-ig-publisher/issues/709
- Will also confirm "Testing" tab page support including notes fragment.

**Comment by rettema** [comment]
The new fhir-ig-publisher issue https://github.com/HL7/fhir-ig-publisher/issues/709 is actually a SUSHI issue https://github.com/FHIR/sushi/issues/1296

**Comment by rettema** [comment]
See updated page for intro example - http://wildfhir4.aegis.net/ig/dev-satisfaction-r4/0.3.0/StructureDefinition-dev-satisfaction-observation.html

**Review by lmckenzi — APPROVED** [review]
Ok

**Pull request merged**
