### PR TITLE
Add nav tabs

### PR DESCRIPTION
**Pull request by Healthedata1**
this commit adds nav tabs to all the resources as GG requested.  it also reduces redundant code by using two include files.

tested on CRD, sample-ig and my test ig.

a couple of screenshots:

navtabs2
navtabs1

### CODE REVIEW

**Comment by lmckenzi** [comment]
I'm fine with the change in principle, but the word "Content" doesn't make sense everywhere.  Its "ok" for profiles and perhaps works for code systems and value sets because those resources *have* content.  However, for the example template, it'd be better if the tab just said "narrative" or "human readable" and we dropped the narrative heading.  Also, can you make a commit to resolve the conflicts?

**Comment by Healthedata1** [comment]
OK will make those changes. I agree but did not want to change the text just apply the tabs everywhere.

**Comment by Healthedata1** [comment]
I will make the changes to the tab names and drop the narrative heading first then resolve the conflicts here

**Comment by lmckenzi** [comment]
Why did you remove the paragraph that indicated the 'id' from the various tabs?  The id matters...

**Comment by Healthedata1** [comment]
I don't know what you mean,   I removed these meaningless redundent paragraphs:
removed lines

**Comment by Healthedata1** [comment]
the id is still in the h2 header?

**Comment by Healthedata1** [comment]
the nav tabs fragments have the includes id variable  include.id which == {{[id]}}

`<a href="{{include.type}}-{{include.id}}-mappings.html">Mappings</a>`

**Comment by Healthedata1** [comment]
could also use page variable too like
---
id: {{{id]}}
type: {{[type]}}
---

and then do this instaed:

<a href="{{ipage.type}}-{{ipage.id}}-mappings.html">Mappings</a>

**Comment by Healthedata1** [comment]
is that what you mean?

**Comment by lmckenzi** [comment]
Old content was stuff like this: `<p>Definitions for the {{[id]}} Extension</p>`
The h2 doesn't include the id in the rendered text.  

(And I don't want us using page variables.  They cause issues in XHTML and we want to minimize the complexity of the markdown)

**Comment by Healthedata1** [comment]
yes I removed them since the are redundant and add no new information for the reader to experience since they repeat  the title.   I assumed since you wanted the text 'narrative' removed you want all the meaningless introductory text removed.  No matter can put them back.

**Comment by lmckenzi** [comment]
My concern is that id and title aren't the same.  Are you referring to a title appearing somewhere other than the <h3>?

**Comment by Healthedata1** [comment]
mmm let me check it out again....

**Comment by Healthedata1** [comment]
OK I see ... titles are using {{[title]}} and not {{[id]}}    will add back in sorry...

**Comment by Healthedata1** [comment]
I will:
1. close this commit
1.  merge branch with master
1.  create a new PR
1. redo the conflicts in the PR  (since my fork is not syncing correctly )

**Pull request closed without merging**
